apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::571692752379:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-13UCP5583GPJJ
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-29T19:47:23Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1621"
  uid: c35a55e6-7911-4cc4-97c8-28a2eb7fe33d
